initSearch: true
server:
  port: 9999
db:
  auto: false
  username: postgres
  password: passowrd
  host: ip
  port: 5432
  name: shuyu_blog
  timeZone: Asia/Shanghai
meilisearch:
  apiHost: http://ip:7700
  apiKey: XIAOYUZUISHUAI
redis:
  db: 2
  addr: ip:6379
  poolSize: 20
  password:
  timeout: 10
email:
  username: Your Username
  password: Your Password
  host: smtp.163.com
  addr: smtp.163.com:25
upload:
  maxImageSize: 5
  maxFileSize: 300
  prefix: static/
  uri: http://127.0.0.1/static/
  path: J:/blog/static
